# javascript === node_js
language: node_js 
# minimum version of node required to run your app
node_js:
  - "14"
#distribution, base image for virtual machine Travis will make for us -- like Ubuntu or Debian
#small version (VM) of Linux 
# dist === OS of our virtual machine for Travis
dist: trusty
#services === pieces of "outside" software we need to run our app -- e.g. databases, modules
services:
  - mongodb
  - redis-server
# array of environment variables, w/c we need to run app in VM .. i.e. from ur config/keys
# env === array of env variables you want set for Travis VM
env:
  # note: these have to be combined in 1 line, or else 2 separate builds will be created
  - NODE_ENV=ci PORT=3000
# after Travis installs node_modules atleast 1 time, will CACHE it for future builds
cache:
  directories:
    # AdvancedNodeStarter dir's node_modules
    - node_modules
    # client dir's node_modules
    - client/node_modules
# commands u want Travis to run at command line, e.g. for SETUP
# install === array of setup command line scripts
install:
  - npm install
  # specific to this project
  - npm run build
# like install, but runs after inistall
script:
  # npm run start === by default / by itself, solely focuses on that command by default. can't run any other commands
  # nohup === will allow other commands to be executed WHILE npm run start is running
  # & === run underlying command in a subshell / "in background mode"
  - nohup npm run start &
  # give ur server time to execute / run itself
  - sleep 3
  - npm run test